//
// auto-generated by op2.py on 2014-03-11 14:18
//

// header
#include "op_lib_cpp.h"
#ifdef VECTORIZE
#include "op_vector.h"
#endif

#define STRIDE(x,y) x
// global constants
extern double gam;
extern double gm1;
extern double cfl;
extern double eps;
extern double mach;
extern double alpha;
extern double qinf[4];
// user kernel files
#include "save_soln_kernel.cpp"
#include "adt_calc_kernel.cpp"
#include "res_calc_kernel.cpp"
#include "bres_calc_kernel.cpp"
#include "update_kernel.cpp"
