//
// auto-generated by op2.m on 29-Oct-2012 09:32:01
//

// header

#include "op_lib_cpp.h"

// global constants

extern float gam;
extern float gm1;
extern float gm1i;
extern float m2;
extern float wtg1[2];
extern float xi1[2];
extern float Ng1[4];
extern float Ng1_xi[4];
extern float wtg2[4];
extern float Ng2[16];
extern float Ng2_xi[32];
extern float minf;
extern float freq;
extern float kappa;
extern float nmode;
extern float mfan;

extern int op2_stride;
#define OP2_STRIDE(arr, idx) arr[idx]


// user kernel files

#include "res_calc_kernel.cpp"
#include "dirichlet_kernel.cpp"
#include "init_cg_kernel.cpp"
#include "spMV_kernel.cpp"
#include "dotPV_kernel.cpp"
#include "updateUR_kernel.cpp"
#include "dotR_kernel.cpp"
#include "updateP_kernel.cpp"
#include "update_kernel.cpp"
