!
! auto-generated by op2.py on 2013-01-16 15:33
!

MODULE SAVE_SOLN_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE OP2_CONSTANTS

#ifdef _OPENMP
  USE OMP_LIB
#endif

! variable declarations
REAL(kind=4) :: loopTimeHostsave_soln
REAL(kind=4) :: loopTimeKernelsave_soln
INTEGER(kind=4) :: numberCalledsave_soln


CONTAINS

! user function
include "save_soln.inc"


! x86 kernel function
SUBROUTINE op_x86_save_soln( &
  &  opDat1,   &
  &  opDat2,   &
  &  opDat3,   &
  & sliceStart, &
  & sliceEnd )

  IMPLICIT NONE

! local variables
  INTEGER(kind=4) :: opDat1
  REAL(kind=8), dimension(0:*) :: opDat2
  REAL(kind=8), dimension(0:*) :: opDat3
  INTEGER(kind=4) :: sliceStart
  INTEGER(kind=4) :: sliceEnd
  INTEGER(kind=4) :: i1

! kernel call
  DO i1 = sliceStart, sliceEnd - 1, 1
    CALL save_soln( &
    & opDat1, &
    & opDat2(i1 * 4:i1 * 4 + 4 - 1), &
    & opDat3(i1 * 4:i1 * 4 + 4 - 1) &
    & )
  END DO
END SUBROUTINE

SUBROUTINE save_soln_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3 )

  IMPLICIT NONE
  character(len=10), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3

  type ( op_arg ) , dimension(3) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4) :: returnMPIHaloExchange
  INTEGER(kind=4) :: returnSetKernelTiming
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality
  type ( op_set_core ) , POINTER :: opSet2Core
  REAL(kind=8), POINTER, dimension(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  type ( op_set_core ) , POINTER :: opSet3Core
  REAL(kind=8), POINTER, dimension(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality


  type ( op_dat_core ) , POINTER :: opDat1Core
  type ( op_dat_core ) , POINTER :: opDat2Core
  type ( op_dat_core ) , POINTER :: opDat3Core

  INTEGER(kind=4) :: threadID
  INTEGER(kind=4) :: numberOfThreads
  INTEGER(kind=4) :: sliceStart
  INTEGER(kind=4) :: sliceEnd
  INTEGER(kind=4) :: partitionSize
  INTEGER(kind=4), dimension(1:8) :: timeArrayStart
  INTEGER(kind=4), dimension(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTimeHost
  REAL(kind=8) :: endTimeHost
  REAL(kind=8) :: startTimeKernel
  REAL(kind=8) :: endTimeKernel
  REAL(kind=8) :: accumulatorHostTime
  REAL(kind=8) :: accumulatorKernelTime
  INTEGER(kind=4) :: i1
  INTEGER(kind=4) :: i10
  INTEGER(kind=4) :: i11

  INTEGER(kind=4), dimension(:), ALLOCATABLE :: reductionArrayHost1

  IF (set%setPtr%size .EQ. 0) THEN
    RETURN
  END IF

  numberCalledsave_soln = numberCalledsave_soln+ 1

  call date_and_time(values=timeArrayStart)
  startTimeHost = 1.00000 * timeArrayStart(8) + &
  & 1000.00 * timeArrayStart(7) + &
  & 60000 * timeArrayStart(6) + &
  & 3600000 * timeArrayStart(5)

#ifdef _OPENMP
  numberOfThreads = omp_get_max_threads()
#else
  numberOfThreads = 1
#endif

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim
  opDat1Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat1Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)

  CALL c_f_pointer(opArg1%data,opDat1Local)
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))


  call date_and_time(values=timeArrayEnd)
  endTimeHost = 1.00000 * timeArrayEnd(8) + &
  & 1000 * timeArrayEnd(7)  + &
  & 60000 * timeArrayEnd(6) + &
  & 3600000 * timeArrayEnd(5)

  accumulatorHostTime = endTimeHost - startTimeHost
  loopTimeHostsave_soln = loopTimeHostsave_soln + accumulatorHostTime

  call date_and_time(values=timeArrayStart)
  startTimeKernel = 1.00000 * timeArrayStart(8) + &
  & 1000 * timeArrayStart(7) + &
  & 60000 * timeArrayStart(6) + &
  & 3600000 * timeArrayStart(5)

  !$OMP PARALLEL DO private (sliceStart,sliceEnd,i1,threadID)
  DO i1 = 0, numberOfThreads - 1, 1
    sliceStart = opSetCore%size * i1 / numberOfThreads
    sliceEnd = opSetCore%size * (i1 + 1) / numberOfThreads
    threadID = omp_get_thread_num()
    CALL op_x86_save_soln( &
      & opDat1Local, &
      & opDat2Local, &
      & opDat3Local, &
      & sliceStart, &
      & sliceEnd)
  END DO
  !$OMP END PARALLEL DO

  call date_and_time(values=timeArrayEnd)
  endTimeKernel = 1.00000 * timeArrayEnd(8) + &
  & 1000 * timeArrayEnd(7) + &
  & 60000 * timeArrayEnd(6) + &
  & 3600000 * timeArrayEnd(5)

  accumulatorKernelTime = endTimeKernel - startTimeKernel
  loopTimeKernelsave_soln = loopTimeKernelsave_soln + accumulatorKernelTime

  call date_and_time(values=timeArrayStart)
  startTimeHost = 1.00000 * timeArrayStart(8) + &
  & 1000.00 * timeArrayStart(7) + &
  & 60000 * timeArrayStart(6) + &
  & 3600000 * timeArrayStart(5)

  call date_and_time(values=timeArrayEnd)
  endTimeHost = 1.00000 * timeArrayEnd(8) + &
  1000 * timeArrayEnd(7) + &
  60000 * timeArrayEnd(6) + &
  3600000 * timeArrayEnd(5)

  accumulatorHostTime = endTimeHost - startTimeHost
  loopTimeHostsave_soln = loopTimeHostsave_soln + accumulatorHostTime

  returnSetKernelTiming = setKernelTime(0 , userSubroutine, &
  & accumulatorKernelTime / 1000.00,0.00000,0.00000)
END SUBROUTINE
END MODULE SAVE_SOLN_MODULE
