#!/bin/sh

#PBS -lwalltime=10:00:00
#PBS -lselect=1:ncpus=16:mem=70gb
#PBS -lplace=excl
#PBS -W block=true
#PBS -q sandyb

module load intel-suite/2013

PBS_O_WORKDIR=/home/fl1612/Sparse-Tiling/OP2-Common-final/apps/c/airfoil/airfoil_tiling/dp/sandyb/

cd $PBS_O_WORKDIR

cat /proc/cpuinfo > machine.txt

export KMP_AFFINITY=verbose,scatter

#for i in {1..3} 
#do
  ./airfoil_openmp
#done

#for i in {1..3}
#do
  ./airfoil_openmp_unstaged
#done

for j in 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000 
do
#    for i in {1..3}
#    do
        ./airfoil_tile_2loop_openmp $j "times_tile_2loop_"$j"_tot.txt" "times_tile_2loop_"$j"_ONLY.txt"
#    done
done
