Document: op2-common
Title: Debian op2-common Manual
Author: <insert document author here>
Abstract: This manual describes what op2-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/op2-common/op2-common.sgml.gz

Format: postscript
Files: /usr/share/doc/op2-common/op2-common.ps.gz

Format: text
Files: /usr/share/doc/op2-common/op2-common.text.gz

Format: HTML
Index: /usr/share/doc/op2-common/html/index.html
Files: /usr/share/doc/op2-common/html/*.html
