#!/bin/sh

#PBS -lwalltime=10:00:00
#PBS -lselect=1:ncpus=12:mem=8gb:westmere=true
#PBS -lplace=excl
#PBS -W block=true
#PBS -q pqkelly

module load intel-suite/2013

PBS_O_WORKDIR=/home/fl1612/Sparse-Tiling/OP2-Common-final/apps/c/airfoil/airfoil_tiling/dp/x5650/

cd $PBS_O_WORKDIR

cat /proc/cpuinfo > machine.txt

export KMP_AFFINITY=verbose,scatter
export OMP_NUM_THREADS=1


#for i in {1..3} 
#do
#  ./airfoil_openmp
#done

#for i in {1..3}
#do
#  ./airfoil_openmp_unstaged
#done

#for j in 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000
for j in 9500 10000 10500 11000 11500 12000 12500 13000 13500 14000 14500 15000 
do
    for i in {1..3}
    do
        ./airfoil_tile_2loop_openmp $j "times_tile_2loop_"$j"_tot.txt" "times_tile_2loop_"$j"_ONLY.txt"
    done
done
