!
! auto-generated by op2.py on 2015-01-26 23:17
!

MODULE GATHER_FUN_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: gather_fun
SUBROUTINE gather_fun(a1,a2,a3,a4,b)

    USE kinds_mod,ONLY: rlk

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: a1,a2,a3,a4
    REAL(KIND=rlk), DIMENSION(4), INTENT(OUT) :: b

    b(1) = a1
    b(2) = a2
    b(3) = a3
    b(4) = a4

  END SUBROUTINE gather_fun


SUBROUTINE op_wrap_gather_fun( &
& opDat1Local, &
& opDat5Local, &
& opDat1Map, &
& opDat1MapDim, &
& bottom,top)
real(8) opDat1Local(1,*)
real(8) opDat5Local(4,*)
INTEGER(kind=4) opDat1Map(*)
INTEGER(kind=4) opDat1MapDim
INTEGER(kind=4) bottom,top,i1
INTEGER(kind=4) map1idx, map2idx, map3idx, map4idx

DO i1 = bottom, top-1, 1
  map1idx = opDat1Map(1 + i1 * opDat1MapDim + 0)+1
  map2idx = opDat1Map(1 + i1 * opDat1MapDim + 1)+1
  map3idx = opDat1Map(1 + i1 * opDat1MapDim + 2)+1
  map4idx = opDat1Map(1 + i1 * opDat1MapDim + 3)+1
! kernel call
CALL gather_fun( &
  & opDat1Local(1,map1idx), &
  & opDat1Local(1,map2idx), &
  & opDat1Local(1,map3idx), &
  & opDat1Local(1,map4idx), &
  & opDat5Local(1,i1+1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE gather_fun_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5

type ( op_arg ) , DIMENSION(5) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat1Map
INTEGER(kind=4) :: opDat1MapDim
real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
LOGICAL :: firstTime_gather_fun = .TRUE.
type ( c_ptr )  :: planRet_gather_fun
type ( op_plan ) , POINTER :: actualPlan_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: ncolblk_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: blkmap_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: nelems_gather_fun
INTEGER(kind=4), POINTER, DIMENSION(:) :: offset_gather_fun
INTEGER(kind=4), DIMENSION(1:5) :: indirectionDescriptorArray
INTEGER(kind=4) :: numberOfIndirectOpDats
INTEGER(kind=4) :: blockOffset
INTEGER(kind=4) :: nblocks
INTEGER(kind=4) :: partitionSize
INTEGER(kind=4) :: blockID
INTEGER(kind=4) :: nelem
INTEGER(kind=4) :: offset_b


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 5

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5

returnSetKernelTiming = setKernelTime(27 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000,0.00000, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  partitionSize = 0

  numberOfThreads = omp_get_max_threads()
  indirectionDescriptorArray(1) = 0
  indirectionDescriptorArray(2) = 0
  indirectionDescriptorArray(3) = 0
  indirectionDescriptorArray(4) = 0
  indirectionDescriptorArray(5) = -1

  numberOfIndirectOpDats = 1

  planRet_gather_fun = FortranPlanCaller( &
  & userSubroutine//C_NULL_CHAR, &
  & set%setCPtr, &
  & partitionSize, &
  & numberOfOpDats, &
  & opArgArray, &
  & numberOfIndirectOpDats, &
  & indirectionDescriptorArray,2)

  CALL c_f_pointer(planRet_gather_fun,actualPlan_gather_fun)
  CALL c_f_pointer(actualPlan_gather_fun%ncolblk,ncolblk_gather_fun,(/actualPlan_gather_fun%ncolors_core/))
  CALL c_f_pointer(actualPlan_gather_fun%blkmap,blkmap_gather_fun,(/actualPlan_gather_fun%nblocks/))
  CALL c_f_pointer(actualPlan_gather_fun%offset,offset_gather_fun,(/actualPlan_gather_fun%nblocks/))
  CALL c_f_pointer(actualPlan_gather_fun%nelems,nelems_gather_fun,(/actualPlan_gather_fun%nblocks/))

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat1MapDim = getMapDimFromOpArg(opArg1)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg1%map_data,opDat1Map,(/opSetCore%size*opDat1MapDim/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))


  blockOffset = 0

  DO i1 = 0, actualPlan_gather_fun%ncolors-1, 1
    IF (i1 .EQ. actualPlan_gather_fun%ncolors_core) THEN
      CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
    END IF

    nblocks = ncolblk_gather_fun(i1 + 1)
    !$OMP PARALLEL DO private (threadID, blockID, nelem, offset_b)
    DO i2 = 0, nblocks-1, 1
      threadID = omp_get_thread_num()
      blockID = blkmap_gather_fun(i2+blockOffset+1)
      nelem = nelems_gather_fun(blockID+1)
      offset_b = offset_gather_fun(blockID+1)
      CALL op_wrap_gather_fun( &
      & opDat1Local, &
      & opDat5Local, &
      & opDat1Map, &
      & opDat1MapDim, &
      & offset_b, offset_b+nelem)
    END DO
    !$OMP END PARALLEL DO
    blockOffset = blockOffset + nblocks
  END DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(27 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, actualPlan_gather_fun%transfer,actualPlan_gather_fun%transfer2, 1)
END SUBROUTINE
END MODULE