!
! auto-generated by op2.py on 2015-01-26 18:29
!

MODULE GETACC_SCATTER_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getacc_scatter
SUBROUTINE getacc_scatter(cnmass,rho,cnwt,cnfx,cnfy, &
&                           ndmass1,ndmass2,ndmass3,ndmass4, &
&                           ndarea1,ndarea2,ndarea3,ndarea4, &
&                           ndub1,ndub2,ndub3,ndub4, &
&                           ndvb1,ndvb2,ndvb3,ndvb4)

    USE kinds_mod,ONLY: ink,rlk
    USE reals_mod,    ONLY: zerocut

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: rho
    REAL(KIND=rlk), INTENT(INOUT) :: ndarea1,ndarea2,ndarea3,ndarea4, &
&                           ndub1,ndub2,ndub3,ndub4, &
&                           ndvb1,ndvb2,ndvb3,ndvb4, &
&                           ndmass1,ndmass2,ndmass3,ndmass4
    REAL(KIND=rlk),DIMENSION(4),INTENT(IN) :: cnmass,cnwt,cnfx,cnfy
    INTEGER(KIND=ink) :: jj,ii

    jj=1_ink
    IF (cnmass(jj).GT.zerocut) THEN
      ndmass1=ndmass1+cnmass(jj)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (cnmass(ii).GT.zerocut) THEN
        ndmass1=ndmass1+cnmass(ii)
      ELSE
        ndmass1=ndmass1+rho*cnwt(jj)
      ENDIF
    ENDIF
    ndarea1=ndarea1+cnwt(jj)
    ndub1=ndub1+cnfx(jj)
    ndvb1=ndvb1+cnfy(jj)

    jj=2_ink
    IF (cnmass(jj).GT.zerocut) THEN
      ndmass2=ndmass2+cnmass(jj)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (cnmass(ii).GT.zerocut) THEN
        ndmass2=ndmass2+cnmass(ii)
      ELSE
        ndmass2=ndmass2+rho*cnwt(jj)
      ENDIF
    ENDIF
    ndarea2=ndarea2+cnwt(jj)
    ndub2=ndub2+cnfx(jj)
    ndvb2=ndvb2+cnfy(jj)

    jj=3_ink
    IF (cnmass(jj).GT.zerocut) THEN
      ndmass3=ndmass3+cnmass(jj)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (cnmass(ii).GT.zerocut) THEN
        ndmass3=ndmass3+cnmass(ii)
      ELSE
        ndmass3=ndmass3+rho*cnwt(jj)
      ENDIF
    ENDIF
    ndarea3=ndarea3+cnwt(jj)
    ndub3=ndub3+cnfx(jj)
    ndvb3=ndvb3+cnfy(jj)

    jj=4_ink
    IF (cnmass(jj).GT.zerocut) THEN
      ndmass4=ndmass4+cnmass(jj)
    ELSE
      ii=jj-1_ink
      IF (ii.EQ.0_ink) ii=4_ink
      IF (cnmass(ii).GT.zerocut) THEN
        ndmass4=ndmass4+cnmass(ii)
      ELSE
        ndmass4=ndmass4+rho*cnwt(jj)
      ENDIF
    ENDIF
    ndarea4=ndarea4+cnwt(jj)
    ndub4=ndub4+cnfx(jj)
    ndvb4=ndvb4+cnfy(jj)

  END SUBROUTINE getacc_scatter


SUBROUTINE op_wrap_getacc_scatter( &
  & opDat6Local, &
  & opDat10Local, &
  & opDat14Local, &
  & opDat18Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Local, &
  & opDat6Map, &
  & opDat6MapDim, &
  & bottom,top)
  real(8) opDat6Local(1,*)
  real(8) opDat10Local(1,*)
  real(8) opDat14Local(1,*)
  real(8) opDat18Local(1,*)
  real(8) opDat1Local(4,*)
  real(8) opDat2Local(1,*)
  real(8) opDat3Local(4,*)
  real(8) opDat4Local(4,*)
  real(8) opDat5Local(4,*)
  INTEGER(kind=4) opDat6Map(*)
  INTEGER(kind=4) opDat6MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map6idx, map7idx, map8idx, map9idx

  DO i1 = bottom, top-1, 1
    map6idx = opDat6Map(1 + i1 * opDat6MapDim + 0)+1
    map7idx = opDat6Map(1 + i1 * opDat6MapDim + 1)+1
    map8idx = opDat6Map(1 + i1 * opDat6MapDim + 2)+1
    map9idx = opDat6Map(1 + i1 * opDat6MapDim + 3)+1
! kernel call
  CALL getacc_scatter( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1,i1+1), &
    & opDat4Local(1,i1+1), &
    & opDat5Local(1,i1+1), &
    & opDat6Local(1,map6idx), &
    & opDat6Local(1,map7idx), &
    & opDat6Local(1,map8idx), &
    & opDat6Local(1,map9idx), &
    & opDat10Local(1,map6idx), &
    & opDat10Local(1,map7idx), &
    & opDat10Local(1,map8idx), &
    & opDat10Local(1,map9idx), &
    & opDat14Local(1,map6idx), &
    & opDat14Local(1,map7idx), &
    & opDat14Local(1,map8idx), &
    & opDat14Local(1,map9idx), &
    & opDat18Local(1,map6idx), &
    & opDat18Local(1,map7idx), &
    & opDat18Local(1,map8idx), &
    & opDat18Local(1,map9idx) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE getacc_scatter_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8, &
  & opArg9, &
  & opArg10, &
  & opArg11, &
  & opArg12, &
  & opArg13, &
  & opArg14, &
  & opArg15, &
  & opArg16, &
  & opArg17, &
  & opArg18, &
  & opArg19, &
  & opArg20, &
  & opArg21 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8
  type ( op_arg ) , INTENT(IN) :: opArg9
  type ( op_arg ) , INTENT(IN) :: opArg10
  type ( op_arg ) , INTENT(IN) :: opArg11
  type ( op_arg ) , INTENT(IN) :: opArg12
  type ( op_arg ) , INTENT(IN) :: opArg13
  type ( op_arg ) , INTENT(IN) :: opArg14
  type ( op_arg ) , INTENT(IN) :: opArg15
  type ( op_arg ) , INTENT(IN) :: opArg16
  type ( op_arg ) , INTENT(IN) :: opArg17
  type ( op_arg ) , INTENT(IN) :: opArg18
  type ( op_arg ) , INTENT(IN) :: opArg19
  type ( op_arg ) , INTENT(IN) :: opArg20
  type ( op_arg ) , INTENT(IN) :: opArg21

  type ( op_arg ) , DIMENSION(21) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat6Map
  INTEGER(kind=4) :: opDat6MapDim
  real(8), POINTER, DIMENSION(:) :: opDat6Local
  INTEGER(kind=4) :: opDat6Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat10Map
  INTEGER(kind=4) :: opDat10MapDim
  real(8), POINTER, DIMENSION(:) :: opDat10Local
  INTEGER(kind=4) :: opDat10Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat14Map
  INTEGER(kind=4) :: opDat14MapDim
  real(8), POINTER, DIMENSION(:) :: opDat14Local
  INTEGER(kind=4) :: opDat14Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat18Map
  INTEGER(kind=4) :: opDat18MapDim
  real(8), POINTER, DIMENSION(:) :: opDat18Local
  INTEGER(kind=4) :: opDat18Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat4Local
  INTEGER(kind=4) :: opDat4Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat5Local
  INTEGER(kind=4) :: opDat5Cardinality


  INTEGER(kind=4) :: i1

  numberOfOpDats = 21

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8
  opArgArray(9) = opArg9
  opArgArray(10) = opArg10
  opArgArray(11) = opArg11
  opArgArray(12) = opArg12
  opArgArray(13) = opArg13
  opArgArray(14) = opArg14
  opArgArray(15) = opArg15
  opArgArray(16) = opArg16
  opArgArray(17) = opArg17
  opArgArray(18) = opArg18
  opArgArray(19) = opArg19
  opArgArray(20) = opArg20
  opArgArray(21) = opArg21

  returnSetKernelTiming = setKernelTime(10 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000,0.00000, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat6MapDim = getMapDimFromOpArg(opArg6)
  opDat10Cardinality = opArg10%dim * getSetSizeFromOpArg(opArg10)
  opDat10MapDim = getMapDimFromOpArg(opArg10)
  opDat14Cardinality = opArg14%dim * getSetSizeFromOpArg(opArg14)
  opDat14MapDim = getMapDimFromOpArg(opArg14)
  opDat18Cardinality = opArg18%dim * getSetSizeFromOpArg(opArg18)
  opDat18MapDim = getMapDimFromOpArg(opArg18)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg6%map_data,opDat6Map,(/opSetCore%size*opDat6MapDim/))
  CALL c_f_pointer(opArg10%data,opDat10Local,(/opDat10Cardinality/))
  CALL c_f_pointer(opArg10%map_data,opDat10Map,(/opSetCore%size*opDat10MapDim/))
  CALL c_f_pointer(opArg14%data,opDat14Local,(/opDat14Cardinality/))
  CALL c_f_pointer(opArg14%map_data,opDat14Map,(/opSetCore%size*opDat14MapDim/))
  CALL c_f_pointer(opArg18%data,opDat18Local,(/opDat18Cardinality/))
  CALL c_f_pointer(opArg18%map_data,opDat18Map,(/opSetCore%size*opDat18MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_getacc_scatter( &
  & opDat6Local, &
  & opDat10Local, &
  & opDat14Local, &
  & opDat18Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Local, &
  & opDat6Map, &
  & opDat6MapDim, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(10 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000,0.00000, 1)
END SUBROUTINE
END MODULE