!
! auto-generated by op2.py on 2015-01-26 23:17
!

MODULE GETDT_MINLOC_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_minloc
SUBROUTINE getdt_minloc(rscratch11,elidx,w1,ii)

    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), INTENT(IN) :: rscratch11
    INTEGER(KIND=ink), INTENT(INOUT) :: ii
    INTEGER(KIND=ink), INTENT(IN) :: elidx
    REAL(KIND=rlk), INTENT(INOUT) :: w1

    IF ((w1.EQ.rscratch11).AND.(ii.GT.elidx)) THEN
      ii = elidx
    ELSE
      ii = MIN(ii,HUGE(1_ink))
    ENDIF

  END SUBROUTINE getdt_minloc


SUBROUTINE op_wrap_getdt_minloc( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& bottom,top)
real(8) opDat1Local(1,*)
integer(4) opDat2Local(1,*)
real(8) opDat3Local(1)
integer(4) opDat4Local(1)
INTEGER(kind=4) bottom,top,i1

DO i1 = bottom, top-1, 1
! kernel call
CALL getdt_minloc( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(1), &
  & opDat4Local(1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE getdt_minloc_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4

type ( op_arg ) , DIMENSION(4) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

integer(4), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
integer(4), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer

integer(4), DIMENSION(:), ALLOCATABLE :: reductionArrayHost4

INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 4

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4

returnSetKernelTiming = setKernelTime(8 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000,0.00000, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)


  numberOfThreads = omp_get_max_threads()

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local, (/opArg3%dim/))
  CALL c_f_pointer(opArg4%data,opDat4Local, (/opArg4%dim/))

  allocate( reductionArrayHost4(numberOfThreads * ((1-1)/64+1)*64) )
  DO i1 = 1, numberOfThreads+1-1, 1
    DO i2 = 1, 1+1-1, 1
      reductionArrayHost4((i1 - 1) * ((1-1)/64+1)*64 + i2) = opDat4Local(i2)
    END DO
  END DO

  !$OMP PARALLEL DO private (sliceStart,sliceEnd,i1,threadID)
  DO i1 = 0, numberOfThreads-1, 1
    sliceStart = opSetCore%size * i1 / numberOfThreads
    sliceEnd = opSetCore%size * (i1 + 1) / numberOfThreads
    threadID = omp_get_thread_num()
! kernel call
    CALL op_wrap_getdt_minloc( &
    & opDat1Local, &
    & opDat2Local, &
    & opDat3Local, &
    & reductionArrayHost4(threadID * ((1-1)/64+1)*64 + 1), &
    & sliceStart, sliceEnd)
  END DO
  !$OMP END PARALLEL DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  DO i1 = 1, numberOfThreads+1-1, 1
    opDat4Local = MIN(opDat4Local, reductionArrayHost4((i1 - 1) * ((1-1)/64+1)*64 + 1))
  END DO

  deallocate( reductionArrayHost4 )

  CALL op_mpi_reduce_int(opArg4,opArg4%data)

  call op_timers_core(endTime)

  dataTransfer = 0.0
  dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
  dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2)
  dataTransfer = dataTransfer + opArg3%size
  dataTransfer = dataTransfer + opArg4%size * 2.d0
  returnSetKernelTiming = setKernelTime(8 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, dataTransfer, 0.00000, 1)
END SUBROUTINE
END MODULE