!
! auto-generated by op2.py on 2015-01-26 18:29
!

MODULE GETDT_CFL_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getdt_cfl
SUBROUTINE getdt_cfl(rscratch11,rho,csqrd,qq,elx,ely,zdtnotreg,zmidlength)

    USE kinds_mod,ONLY: rlk,ink
!    USE geometry_mod,    ONLY: dlm,dln
    USE reals_mod,       ONLY: ccut,zcut,dt_max
    USE parameters_mod,ONLY: N_SHAPE

    implicit none

    REAL(KIND=rlk), DIMENSION(4), INTENT(IN) :: elx,ely
    REAL(KIND=rlk), INTENT(IN) :: rho,csqrd,qq
    REAL(KIND=rlk), INTENT(OUT) :: rscratch11
    INTEGER(KIND=ink), INTENT(IN) :: zdtnotreg,zmidlength !need to inline this

    REAL(KIND=rlk) :: w1,w2,w3
    !For dlm and dln
    REAL(KIND=rlk)                              :: x1,x2,y1,y2
    REAL(KIND=rlk),DIMENSION(N_SHAPE)            :: res

    IF (zdtnotreg) THEN
      rscratch11=dt_max
    ELSE
      w1=MAX(rho,zcut)
      w2=MAX(ccut,csqrd)+2.0_rlk*qq/w1
      IF (zmidlength) THEN
        x1=elx(1)+elx(2)
        x2=elx(3)+elx(4)
        y1=ely(1)+ely(2)
        y2=ely(3)+ely(4)
        x1=0.5_rlk*(x1-x2)
        y1=0.5_rlk*(y1-y2)
        res(1)=x1*x1+y1*y1
        x1=elx(3)+elx(2)
        x2=elx(1)+elx(4)
        y1=ely(3)+ely(2)
        y2=ely(1)+ely(4)
        x1=0.5_rlk*(x1-x2)
        y1=0.5_rlk*(y1-y2)
        res(2)=x1*x1+y1*y1
        res(3)=res(1)
        res(4)=res(2)
        w1=MIN(res(1),res(2),res(3),res(4))
      ELSE
        w3=(ely(3)-ely(4))*(ely(3)-ely(4))+(elx(3)-elx(4))*(elx(3)-elx(4))
        !denom(elx(3),ely(3),elx(4),ely(4))
        IF (w3.LT.zcut) THEN
          res(1)=(0.5_rlk*(elx(1)+elx(2))-elx(3))*(0.5_rlk*(elx(1)+elx(2))-elx(3))+ &
    &         (0.5_rlk*(ely(1)+ely(2))-ely(3))*(0.5_rlk*(ely(1)+ely(2))-ely(3))
          !distpp(elx(1),ely(1),elx(2),ely(2),elx(3),ely(3))
        ELSE
          res(1)= 0.5_rlk*(ely(3)-ely(4))*(elx(1)+elx(2))+0.5_rlk*(ely(1)+ely(2))*(elx(4)-elx(3))+ely(4)*elx(3)-ely(3)*elx(4)
          res(1) = res(1)*res(1)/w3
    !      distpl(elx(1),ely(1),elx(2),ely(2),elx(3),ely(3),elx(4),   &
    !&                   ely(4))/w3
        ENDIF
        w3=(ely(4)-ely(1))*(ely(4)-ely(1))+(elx(4)-elx(1))*(elx(4)-elx(1))
        !denom(elx(4),ely(4),elx(1),ely(1))
        IF (w3.LT.zcut) THEN
          res(2)=(0.5_rlk*(elx(2)+elx(3))-elx(4))*(0.5_rlk*(elx(2)+elx(3))-elx(4))+ &
    &         (0.5_rlk*(ely(2)+ely(3))-ely(4))*(0.5_rlk*(ely(2)+ely(3))-ely(4))
          !distpp(elx(2),ely(2),elx(3),ely(3),elx(4),ely(4))
        ELSE
          res(2)= 0.5_rlk*(ely(4)-ely(1))*(elx(2)+elx(3))+0.5_rlk*(ely(2)+ely(3))*(elx(1)-elx(4))+ely(1)*elx(4)-ely(4)*elx(1)
          res(2) = res(2)*res(2)/w3
    !      distpl(elx(2),ely(2),elx(3),ely(3),elx(4),ely(4),elx(1),   &
    !&                   ely(1))/w3
        ENDIF
        w3=(ely(1)-ely(2))*(ely(1)-ely(2))+(elx(1)-elx(2))*(elx(1)-elx(2))
        !denom(elx(1),ely(1),elx(2),ely(2))
        IF (w3.LT.zcut) THEN
          res(3)=(0.5_rlk*(elx(3)+elx(4))-elx(1))*(0.5_rlk*(elx(3)+elx(4))-elx(1))+ &
    &         (0.5_rlk*(ely(3)+ely(4))-ely(1))*(0.5_rlk*(ely(3)+ely(4))-ely(1))
          !distpp(elx(3),ely(3),elx(4),ely(4),elx(1),ely(1))
        ELSE
          res(3)= 0.5_rlk*(ely(1)-ely(2))*(elx(3)+elx(4))+0.5_rlk*(ely(3)+ely(4))*(elx(2)-elx(1))+ely(2)*elx(1)-ely(1)*elx(2)
          res(3) = res(3)*res(3)/w3
    !      distpl(elx(3),ely(3),elx(4),ely(4),elx(1),ely(1),elx(2),   &
    !&                   ely(2))/w3
        ENDIF
        w3=(ely(2)-ely(3))*(ely(2)-ely(3))+(elx(2)-elx(3))*(elx(2)-elx(3))
        !denom(elx(2),ely(2),elx(3),ely(3))
        IF (w3.LT.zcut) THEN
          res(4)=(0.5_rlk*(elx(4)+elx(1))-elx(2))*(0.5_rlk*(elx(4)+elx(1))-elx(2))+ &
    &         (0.5_rlk*(ely(4)+ely(1))-ely(2))*(0.5_rlk*(ely(4)+ely(1))-ely(2))
          !distpp(elx(4),ely(4),elx(1),ely(1),elx(2),ely(2))
        ELSE
          res(4)=0.5_rlk*(ely(2)-ely(3))*(elx(4)+elx(1))+0.5_rlk*(ely(4)+ely(1))*(elx(3)-elx(2))+ely(3)*elx(2)-ely(2)*elx(3)
          res(4) = res(4)*res(4)/w3
    !      distpl(elx(4),ely(4),elx(1),ely(1),elx(2),ely(2),elx(3),   &
    !&                   ely(3))/w3
        ENDIF
        w1=MIN(res(1),res(2),res(3),res(4))
      ENDIF
      rscratch11=w1/w2
    ENDIF

  END SUBROUTINE getdt_cfl


SUBROUTINE op_wrap_getdt_cfl( &
  & opDat7Local, &
  & opDat8Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Local, &
  & opDat6Local, &
  & opDat7Map, &
  & opDat7MapDim, &
  & bottom,top)
  integer(4) opDat7Local(1,*)
  integer(4) opDat8Local(1,*)
  real(8) opDat1Local(1,*)
  real(8) opDat2Local(1,*)
  real(8) opDat3Local(1,*)
  real(8) opDat4Local(1,*)
  real(8) opDat5Local(4,*)
  real(8) opDat6Local(4,*)
  INTEGER(kind=4) opDat7Map(*)
  INTEGER(kind=4) opDat7MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map7idx

  DO i1 = bottom, top-1, 1
    map7idx = opDat7Map(1 + i1 * opDat7MapDim + 0)+1
! kernel call
  CALL getdt_cfl( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1,i1+1), &
    & opDat4Local(1,i1+1), &
    & opDat5Local(1,i1+1), &
    & opDat6Local(1,i1+1), &
    & opDat7Local(1,map7idx), &
    & opDat8Local(1,map7idx) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE getdt_cfl_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8

  type ( op_arg ) , DIMENSION(8) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat7Map
  INTEGER(kind=4) :: opDat7MapDim
  integer(4), POINTER, DIMENSION(:) :: opDat7Local
  INTEGER(kind=4) :: opDat7Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat8Map
  INTEGER(kind=4) :: opDat8MapDim
  integer(4), POINTER, DIMENSION(:) :: opDat8Local
  INTEGER(kind=4) :: opDat8Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat4Local
  INTEGER(kind=4) :: opDat4Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat5Local
  INTEGER(kind=4) :: opDat5Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat6Local
  INTEGER(kind=4) :: opDat6Cardinality


  INTEGER(kind=4) :: i1

  numberOfOpDats = 8

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8

  returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000,0.00000, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  opDat7MapDim = getMapDimFromOpArg(opArg7)
  opDat8Cardinality = opArg8%dim * getSetSizeFromOpArg(opArg8)
  opDat8MapDim = getMapDimFromOpArg(opArg8)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))
  CALL c_f_pointer(opArg7%map_data,opDat7Map,(/opSetCore%size*opDat7MapDim/))
  CALL c_f_pointer(opArg8%data,opDat8Local,(/opDat8Cardinality/))
  CALL c_f_pointer(opArg8%map_data,opDat8Map,(/opSetCore%size*opDat8MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_getdt_cfl( &
  & opDat7Local, &
  & opDat8Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat5Local, &
  & opDat6Local, &
  & opDat7Map, &
  & opDat7MapDim, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(6 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000,0.00000, 1)
END SUBROUTINE
END MODULE