!
! auto-generated by op2.py on 2015-01-26 23:17
!

MODULE GETFORCE_PRES_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI

USE OMP_LIB


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getforce_pres
SUBROUTINE getforce_pres(pre,elfx,elfy,a1,a3,b1,b3)

    USE kinds_mod,ONLY: rlk

    implicit none

    REAL(KIND=rlk), DIMENSION(4), INTENT(OUT) :: elfx,elfy
    REAL(KIND=rlk), INTENT(IN) :: pre,a1,a3,b1,b3

    REAL(KIND=rlk) :: w1

    w1=pre
    elfx(1)=w1*(-b3+b1)
    elfx(2)=w1*( b3+b1)
    elfx(3)=w1*( b3-b1)
    elfx(4)=w1*(-b3-b1)
    elfy(1)=w1*( a3-a1)
    elfy(2)=w1*(-a3-a1)
    elfy(3)=w1*(-a3+a1)
    elfy(4)=w1*( a3+a1)

  END SUBROUTINE getforce_pres


SUBROUTINE op_wrap_getforce_pres( &
& opDat1Local, &
& opDat2Local, &
& opDat3Local, &
& opDat4Local, &
& opDat5Local, &
& opDat6Local, &
& opDat7Local, &
& bottom,top)
real(8) opDat1Local(1,*)
real(8) opDat2Local(4,*)
real(8) opDat3Local(4,*)
real(8) opDat4Local(1,*)
real(8) opDat5Local(1,*)
real(8) opDat6Local(1,*)
real(8) opDat7Local(1,*)
INTEGER(kind=4) bottom,top,i1

DO i1 = bottom, top-1, 1
! kernel call
CALL getforce_pres( &
  & opDat1Local(1,i1+1), &
  & opDat2Local(1,i1+1), &
  & opDat3Local(1,i1+1), &
  & opDat4Local(1,i1+1), &
  & opDat5Local(1,i1+1), &
  & opDat6Local(1,i1+1), &
  & opDat7Local(1,i1+1) &
  & )
END DO
END SUBROUTINE
SUBROUTINE getforce_pres_host( userSubroutine, set, &
& opArg1, &
& opArg2, &
& opArg3, &
& opArg4, &
& opArg5, &
& opArg6, &
& opArg7 )

IMPLICIT NONE
character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
type ( op_set ) , INTENT(IN) :: set

type ( op_arg ) , INTENT(IN) :: opArg1
type ( op_arg ) , INTENT(IN) :: opArg2
type ( op_arg ) , INTENT(IN) :: opArg3
type ( op_arg ) , INTENT(IN) :: opArg4
type ( op_arg ) , INTENT(IN) :: opArg5
type ( op_arg ) , INTENT(IN) :: opArg6
type ( op_arg ) , INTENT(IN) :: opArg7

type ( op_arg ) , DIMENSION(7) :: opArgArray
INTEGER(kind=4) :: numberOfOpDats
INTEGER(kind=4) :: n_upper
type ( op_set_core ) , POINTER :: opSetCore

real(8), POINTER, DIMENSION(:) :: opDat1Local
INTEGER(kind=4) :: opDat1Cardinality

real(8), POINTER, DIMENSION(:) :: opDat2Local
INTEGER(kind=4) :: opDat2Cardinality

real(8), POINTER, DIMENSION(:) :: opDat3Local
INTEGER(kind=4) :: opDat3Cardinality

real(8), POINTER, DIMENSION(:) :: opDat4Local
INTEGER(kind=4) :: opDat4Cardinality

real(8), POINTER, DIMENSION(:) :: opDat5Local
INTEGER(kind=4) :: opDat5Cardinality

real(8), POINTER, DIMENSION(:) :: opDat6Local
INTEGER(kind=4) :: opDat6Cardinality

real(8), POINTER, DIMENSION(:) :: opDat7Local
INTEGER(kind=4) :: opDat7Cardinality

INTEGER(kind=4) :: threadID
INTEGER(kind=4) :: numberOfThreads
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
REAL(kind=8) :: startTime
REAL(kind=8) :: endTime
INTEGER(kind=4) :: returnSetKernelTiming
INTEGER(kind=4) :: sliceStart
INTEGER(kind=4) :: sliceEnd
REAL(kind=4) :: dataTransfer


INTEGER(kind=4) :: i1,i2,n

numberOfOpDats = 7

opArgArray(1) = opArg1
opArgArray(2) = opArg2
opArgArray(3) = opArg3
opArgArray(4) = opArg4
opArgArray(5) = opArg5
opArgArray(6) = opArg6
opArgArray(7) = opArg7

returnSetKernelTiming = setKernelTime(18 , userSubroutine//C_NULL_CHAR, &
& 0.d0, 0.00000,0.00000, 0)
call op_timers_core(startTime)

n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)


  numberOfThreads = omp_get_max_threads()

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  opDat6Cardinality = opArg6%dim * getSetSizeFromOpArg(opArg6)
  opDat7Cardinality = opArg7%dim * getSetSizeFromOpArg(opArg7)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
  CALL c_f_pointer(opArg6%data,opDat6Local,(/opDat6Cardinality/))
  CALL c_f_pointer(opArg7%data,opDat7Local,(/opDat7Cardinality/))


  !$OMP PARALLEL DO private (sliceStart,sliceEnd,i1,threadID)
  DO i1 = 0, numberOfThreads-1, 1
    sliceStart = opSetCore%size * i1 / numberOfThreads
    sliceEnd = opSetCore%size * (i1 + 1) / numberOfThreads
    threadID = omp_get_thread_num()
! kernel call
    CALL op_wrap_getforce_pres( &
    & opDat1Local, &
    & opDat2Local, &
    & opDat3Local, &
    & opDat4Local, &
    & opDat5Local, &
    & opDat6Local, &
    & opDat7Local, &
    & sliceStart, sliceEnd)
  END DO
  !$OMP END PARALLEL DO
  IF ((n_upper .EQ. 0) .OR. (n_upper .EQ. opSetCore%core_size)) THEN
    CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  END IF

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  dataTransfer = 0.0
  dataTransfer = dataTransfer + opArg1%size * getSetSizeFromOpArg(opArg1)
  dataTransfer = dataTransfer + opArg2%size * getSetSizeFromOpArg(opArg2) * 2.d0
  dataTransfer = dataTransfer + opArg3%size * getSetSizeFromOpArg(opArg3) * 2.d0
  dataTransfer = dataTransfer + opArg4%size * getSetSizeFromOpArg(opArg4)
  dataTransfer = dataTransfer + opArg5%size * getSetSizeFromOpArg(opArg5)
  dataTransfer = dataTransfer + opArg6%size * getSetSizeFromOpArg(opArg6)
  dataTransfer = dataTransfer + opArg7%size * getSetSizeFromOpArg(opArg7)
  returnSetKernelTiming = setKernelTime(18 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime, dataTransfer, 0.00000, 1)
END SUBROUTINE
END MODULE