!
! auto-generated by op2.py on 2015-01-26 18:29
!

MODULE GETQ_CHRISTIENSEN1_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: getq_christiensen1
SUBROUTINE getq_christiensen1(du,dv,dx,dy, &
&             du1,du2,du3,du4,dv1,dv2,dv3,dv4,&
&             dx1,dx2,dx3,dx4,dy1,dy2,dy3,dy4,&
&            ielsd,scratch,iside)
    USE kinds_mod,ONLY: rlk
    USE parameters_mod,ONLY: N_SHAPE
    USE reals_mod,    ONLY: zerocut

    implicit none

    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(IN) :: du,dv,dx,dy, &
&             du1,du2,du3,du4,dv1,dv2,dv3,dv4,&
&             dx1,dx2,dx3,dx4,dy1,dy2,dy3,dy4
    REAL(KIND=rlk), DIMENSION(N_SHAPE), INTENT(OUT) :: scratch
    INTEGER(KIND=ink), INTENT(IN) :: iside
    INTEGER(KIND=ink), DIMENSION(N_SHAPE), INTENT(IN) :: ielsd
    INTEGER(KIND=ink) :: is1,is2,ins
    REAL(KIND=rlk) :: w1,w2,w3,w4,den,uhat,vhat,xhat,yhat

    is1=MOD(iside+2_ink,N_SHAPE)+1_ink
    is2=iside+1_ink

    ! edge 1
    w1=du(is1)
    w2=dv(is1)
    w3=dx(is1)
    w4=dy(is1)
    den=SQRT(w1*w1+w2*w2)
    den=1.0_rlk/MAX(den,zerocut)
    uhat=w1*den
    vhat=w2*den
    den=SQRT(w3*w3+w4*w4)
    den=1.0_rlk/MAX(den,zerocut)
    xhat=w3*den
    yhat=w4*den
    den=w3*xhat+w4*yhat
    w1=(w1*uhat+w2*vhat)/SIGN(MAX(ABS(den),zerocut),den)
    w1=1.0_rlk/SIGN(MAX(ABS(w1),zerocut),w1)
    ins=ielsd(iside)
    ins=MOD(ins,N_SHAPE)+1_ink
    IF (iside.eq.1_ink) THEN
      den=dx1(ins)*xhat+dy1(ins)*yhat
      w2=(du1(ins)*uhat+dv1(ins)*vhat)/                        &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ELSE
      den=dx2(ins)*xhat+dy2(ins)*yhat
      w2=(du2(ins)*uhat+dv2(ins)*vhat)/                        &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ENDIF
    scratch(1)=w2*w1
    ins=ielsd(iside+2_ink)
    ins=MOD(ins+2_ink,N_SHAPE)+1_ink
    IF (iside.eq.1_ink) THEN
      den=dx3(ins)*xhat+dy3(ins)*yhat
      w3=(du3(ins)*uhat+dv3(ins)*vhat)/                        &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ELSE
      den=dx4(ins)*xhat+dy4(ins)*yhat
      w3=(du4(ins)*uhat+dv4(ins)*vhat)/                        &
&          SIGN(MAX(ABS(den),zerocut),den)
    ENDIF
    scratch(2)=w3*w1
    ! edge 2
    w1=du(is2)
    w2=dv(is2)
    w3=dx(is2)
    w4=dy(is2)
    den=SQRT(w1*w1+w2*w2)
    den=1.0_rlk/MAX(den,zerocut)
    uhat=w1*den
    vhat=w2*den
    den=SQRT(w3*w3+w4*w4)
    den=1.0_rlk/MAX(den,zerocut)
    xhat=w3*den
    yhat=w4*den
    den=w3*xhat+w4*yhat
    w1=(w1*uhat+w2*vhat)/SIGN(MAX(ABS(den),zerocut),den)
    w1=1.0_rlk/SIGN(MAX(ABS(w1),zerocut),w1)
    ins=ielsd(iside)
    ins=MOD(ins+2_ink,N_SHAPE)+1_ink
    IF (iside.eq.1_ink) THEN
      den=dx1(ins)*xhat+dy1(ins)*yhat
      w2=(du1(ins)*uhat+dv1(ins)*vhat)/                         &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ELSE
      den=dx2(ins)*xhat+dy2(ins)*yhat
      w2=(du2(ins)*uhat+dv2(ins)*vhat)/                         &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ENDIF
    scratch(3)=w2*w1
    ins=ielsd(iside+2_ink)
    ins=MOD(ins,N_SHAPE)+1_ink
    IF (iside.eq.1_ink) THEN
      den=dx3(ins)*xhat+dy3(ins)*yhat
      w3=(du3(ins)*uhat+dv3(ins)*vhat)/                         &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ELSE
      den=dx4(ins)*xhat+dy4(ins)*yhat
      w3=(du4(ins)*uhat+dv4(ins)*vhat)/                         &
  &        SIGN(MAX(ABS(den),zerocut),den)
    ENDIF
    scratch(4)=w3*w1

  END SUBROUTINE getq_christiensen1


SUBROUTINE op_wrap_getq_christiensen1( &
  & opDat5Local, &
  & opDat9Local, &
  & opDat13Local, &
  & opDat17Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat21Local, &
  & opDat22Local, &
  & opDat23Local, &
  & opDat5Map, &
  & opDat5MapDim, &
  & bottom,top)
  real(8) opDat5Local(4,*)
  real(8) opDat9Local(4,*)
  real(8) opDat13Local(4,*)
  real(8) opDat17Local(4,*)
  real(8) opDat1Local(4,*)
  real(8) opDat2Local(4,*)
  real(8) opDat3Local(4,*)
  real(8) opDat4Local(4,*)
  integer(4) opDat21Local(4,*)
  real(8) opDat22Local(4,*)
  integer(4) opDat23Local(1)
  INTEGER(kind=4) opDat5Map(*)
  INTEGER(kind=4) opDat5MapDim
  INTEGER(kind=4) bottom,top,i1
  INTEGER(kind=4) map5idx, map6idx, map7idx, map8idx

  DO i1 = bottom, top-1, 1
    map5idx = opDat5Map(1 + i1 * opDat5MapDim + 0)+1
    map6idx = opDat5Map(1 + i1 * opDat5MapDim + 1)+1
    map7idx = opDat5Map(1 + i1 * opDat5MapDim + 2)+1
    map8idx = opDat5Map(1 + i1 * opDat5MapDim + 3)+1
! kernel call
  CALL getq_christiensen1( &
    & opDat1Local(1,i1+1), &
    & opDat2Local(1,i1+1), &
    & opDat3Local(1,i1+1), &
    & opDat4Local(1,i1+1), &
    & opDat5Local(1,map5idx), &
    & opDat5Local(1,map6idx), &
    & opDat5Local(1,map7idx), &
    & opDat5Local(1,map8idx), &
    & opDat9Local(1,map5idx), &
    & opDat9Local(1,map6idx), &
    & opDat9Local(1,map7idx), &
    & opDat9Local(1,map8idx), &
    & opDat13Local(1,map5idx), &
    & opDat13Local(1,map6idx), &
    & opDat13Local(1,map7idx), &
    & opDat13Local(1,map8idx), &
    & opDat17Local(1,map5idx), &
    & opDat17Local(1,map6idx), &
    & opDat17Local(1,map7idx), &
    & opDat17Local(1,map8idx), &
    & opDat21Local(1,i1+1), &
    & opDat22Local(1,i1+1), &
    & opDat23Local(1) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE getq_christiensen1_host( userSubroutine, set, &
  & opArg1, &
  & opArg2, &
  & opArg3, &
  & opArg4, &
  & opArg5, &
  & opArg6, &
  & opArg7, &
  & opArg8, &
  & opArg9, &
  & opArg10, &
  & opArg11, &
  & opArg12, &
  & opArg13, &
  & opArg14, &
  & opArg15, &
  & opArg16, &
  & opArg17, &
  & opArg18, &
  & opArg19, &
  & opArg20, &
  & opArg21, &
  & opArg22, &
  & opArg23 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1
  type ( op_arg ) , INTENT(IN) :: opArg2
  type ( op_arg ) , INTENT(IN) :: opArg3
  type ( op_arg ) , INTENT(IN) :: opArg4
  type ( op_arg ) , INTENT(IN) :: opArg5
  type ( op_arg ) , INTENT(IN) :: opArg6
  type ( op_arg ) , INTENT(IN) :: opArg7
  type ( op_arg ) , INTENT(IN) :: opArg8
  type ( op_arg ) , INTENT(IN) :: opArg9
  type ( op_arg ) , INTENT(IN) :: opArg10
  type ( op_arg ) , INTENT(IN) :: opArg11
  type ( op_arg ) , INTENT(IN) :: opArg12
  type ( op_arg ) , INTENT(IN) :: opArg13
  type ( op_arg ) , INTENT(IN) :: opArg14
  type ( op_arg ) , INTENT(IN) :: opArg15
  type ( op_arg ) , INTENT(IN) :: opArg16
  type ( op_arg ) , INTENT(IN) :: opArg17
  type ( op_arg ) , INTENT(IN) :: opArg18
  type ( op_arg ) , INTENT(IN) :: opArg19
  type ( op_arg ) , INTENT(IN) :: opArg20
  type ( op_arg ) , INTENT(IN) :: opArg21
  type ( op_arg ) , INTENT(IN) :: opArg22
  type ( op_arg ) , INTENT(IN) :: opArg23

  type ( op_arg ) , DIMENSION(23) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat5Map
  INTEGER(kind=4) :: opDat5MapDim
  real(8), POINTER, DIMENSION(:) :: opDat5Local
  INTEGER(kind=4) :: opDat5Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat9Map
  INTEGER(kind=4) :: opDat9MapDim
  real(8), POINTER, DIMENSION(:) :: opDat9Local
  INTEGER(kind=4) :: opDat9Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat13Map
  INTEGER(kind=4) :: opDat13MapDim
  real(8), POINTER, DIMENSION(:) :: opDat13Local
  INTEGER(kind=4) :: opDat13Cardinality

  INTEGER(kind=4), POINTER, DIMENSION(:) :: opDat17Map
  INTEGER(kind=4) :: opDat17MapDim
  real(8), POINTER, DIMENSION(:) :: opDat17Local
  INTEGER(kind=4) :: opDat17Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat2Local
  INTEGER(kind=4) :: opDat2Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat3Local
  INTEGER(kind=4) :: opDat3Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat4Local
  INTEGER(kind=4) :: opDat4Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat21Local
  INTEGER(kind=4) :: opDat21Cardinality

  real(8), POINTER, DIMENSION(:) :: opDat22Local
  INTEGER(kind=4) :: opDat22Cardinality

  integer(4), POINTER, DIMENSION(:) :: opDat23Local

  INTEGER(kind=4) :: i1

  numberOfOpDats = 23

  opArgArray(1) = opArg1
  opArgArray(2) = opArg2
  opArgArray(3) = opArg3
  opArgArray(4) = opArg4
  opArgArray(5) = opArg5
  opArgArray(6) = opArg6
  opArgArray(7) = opArg7
  opArgArray(8) = opArg8
  opArgArray(9) = opArg9
  opArgArray(10) = opArg10
  opArgArray(11) = opArg11
  opArgArray(12) = opArg12
  opArgArray(13) = opArg13
  opArgArray(14) = opArg14
  opArgArray(15) = opArg15
  opArgArray(16) = opArg16
  opArgArray(17) = opArg17
  opArgArray(18) = opArg18
  opArgArray(19) = opArg19
  opArgArray(20) = opArg20
  opArgArray(21) = opArg21
  opArgArray(22) = opArg22
  opArgArray(23) = opArg23

  returnSetKernelTiming = setKernelTime(21 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000,0.00000, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat5Cardinality = opArg5%dim * getSetSizeFromOpArg(opArg5)
  opDat5MapDim = getMapDimFromOpArg(opArg5)
  opDat9Cardinality = opArg9%dim * getSetSizeFromOpArg(opArg9)
  opDat9MapDim = getMapDimFromOpArg(opArg9)
  opDat13Cardinality = opArg13%dim * getSetSizeFromOpArg(opArg13)
  opDat13MapDim = getMapDimFromOpArg(opArg13)
  opDat17Cardinality = opArg17%dim * getSetSizeFromOpArg(opArg17)
  opDat17MapDim = getMapDimFromOpArg(opArg17)
  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  opDat2Cardinality = opArg2%dim * getSetSizeFromOpArg(opArg2)
  opDat3Cardinality = opArg3%dim * getSetSizeFromOpArg(opArg3)
  opDat4Cardinality = opArg4%dim * getSetSizeFromOpArg(opArg4)
  opDat21Cardinality = opArg21%dim * getSetSizeFromOpArg(opArg21)
  opDat22Cardinality = opArg22%dim * getSetSizeFromOpArg(opArg22)
  CALL c_f_pointer(opArg5%data,opDat5Local,(/opDat5Cardinality/))
  CALL c_f_pointer(opArg5%map_data,opDat5Map,(/opSetCore%size*opDat5MapDim/))
  CALL c_f_pointer(opArg9%data,opDat9Local,(/opDat9Cardinality/))
  CALL c_f_pointer(opArg9%map_data,opDat9Map,(/opSetCore%size*opDat9MapDim/))
  CALL c_f_pointer(opArg13%data,opDat13Local,(/opDat13Cardinality/))
  CALL c_f_pointer(opArg13%map_data,opDat13Map,(/opSetCore%size*opDat13MapDim/))
  CALL c_f_pointer(opArg17%data,opDat17Local,(/opDat17Cardinality/))
  CALL c_f_pointer(opArg17%map_data,opDat17Map,(/opSetCore%size*opDat17MapDim/))
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))
  CALL c_f_pointer(opArg2%data,opDat2Local,(/opDat2Cardinality/))
  CALL c_f_pointer(opArg3%data,opDat3Local,(/opDat3Cardinality/))
  CALL c_f_pointer(opArg4%data,opDat4Local,(/opDat4Cardinality/))
  CALL c_f_pointer(opArg21%data,opDat21Local,(/opDat21Cardinality/))
  CALL c_f_pointer(opArg22%data,opDat22Local,(/opDat22Cardinality/))
  CALL c_f_pointer(opArg23%data,opDat23Local, (/opArg23%dim/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_getq_christiensen1( &
  & opDat5Local, &
  & opDat9Local, &
  & opDat13Local, &
  & opDat17Local, &
  & opDat1Local, &
  & opDat2Local, &
  & opDat3Local, &
  & opDat4Local, &
  & opDat21Local, &
  & opDat22Local, &
  & opDat23Local, &
  & opDat5Map, &
  & opDat5MapDim, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(21 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000,0.00000, 1)
END SUBROUTINE
END MODULE