#
# !Crown Copyright 2014 AWE.
# !
# ! This file is part of Bookleaf.
# !
# ! Bookleaf is free software: you can redistribute it and/or modify it under
# ! the terms of the GNU General Public License as published by the
# ! Free Software Foundation, either version 3 of the License, or (at your option)
# ! any later version.
# !
# ! Bookleaf is distributed in the hope that it will be useful, but
# ! WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# ! FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# ! details.
# !
# ! You should have received a copy of the GNU General Public License along with
# ! Bookleaf. If not, see http://www.gnu.org/licenses/.
#
#
# Object list
ifndef OPTARGET
OBJ = banner.o       \
      comm.o         \
      common_kernels.o         \
      data.o         \
      error.o        \
      eos.o          \
      geometry.o     \
      geometry_kernels.o     \
      getacc.o       \
      getacc_kernels.o       \
      getdt.o        \
      getdt_kernels.o        \
      getein.o       \
      getein_kernels.o       \
      getforce.o     \
      getforce_kernels.o     \
      gethg.o        \
      getpc_kernels.o        \
      getpc.o        \
      getq_kernels.o         \
      getq.o         \
      getsp.o        \
      halt.o         \
      hydro.o        \
      init.o         \
      init_kernels.o         \
      lagstep.o      \
      lagstep_kernels.o      \
      main.o         \
      mesh.o         \
      read.o         \
      timers.o       \
      utilities.o    \
      write.o
OP2_LIB = -lop2_for_seq
else
ifeq ($(OPTARGET),genseq)
OBJ = banner.o       \
      comm.o         \
      common_kernels.o         \
      data.o         \
      error.o        \
      eos.o          \
      geometry_op.o     \
      getacc_op.o       \
      getdt_op.o        \
      getein_op.o       \
      getforce_op.o     \
      gethg.o        \
      getpc_op.o        \
      getq_op.o         \
      getsp.o        \
      halt.o         \
      hydro.o        \
      init_op.o         \
      lagstep_op.o      \
      main.o         \
      mesh.o         \
      read.o         \
      timers.o       \
      utilities_op.o    \
      write.o
OBJ += $(shell find . -name "*_seqkernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_seq
endif
ifeq ($(OPTARGET),openmp)
OBJ = banner.o       \
      comm.o         \
      common_kernels.o         \
      data.o         \
      error.o        \
      eos.o          \
      geometry_op.o     \
      getacc_op.o       \
      getdt_op.o        \
      getein_op.o       \
      getforce_op.o     \
      gethg.o        \
      getpc_op.o        \
      getq_op.o         \
      getsp.o        \
      halt.o         \
      hydro.o        \
      init_op.o         \
      lagstep_op.o      \
      main.o         \
      mesh.o         \
      read.o         \
      timers.o       \
      utilities_op.o    \
      write.o
OBJ += $(shell find . -name "*_kernel.f90" | sed s/\\.f90/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_openmp
endif
ifeq ($(OPTARGET),cuda)
OBJ = banner.o       \
      comm.o         \
      cudaConfigurationParams.o \
      common_kernels.o         \
      data.o         \
      error.o        \
      eos.o          \
      geometry_op.o     \
      getacc_op.o       \
      getdt_op.o        \
      getein_op.o       \
      getforce_op.o     \
      gethg.o        \
      getpc_op.o        \
      getq_op.o         \
      getsp.o        \
      halt.o         \
      hydro.o        \
      init_op.o         \
      lagstep_op.o      \
      main.o         \
      mesh.o         \
      read.o         \
      timers.o       \
      utilities_op.o    \
      write.o
OBJ += $(shell find . -name "*_kernel.CUF" | sed s/\\.CUF/\\.o/g | sed s/\\.\\///g | tr "\n" ' ')
OP2_LIB = -lop2_for_cuda -Mcuda=cuda6.0,cc35 -lcuda
endif
endif
