!
! auto-generated by op2.py on 2015-01-26 18:29
!

MODULE SET_ZERO4_MODULE
USE OP2_FORTRAN_DECLARATIONS
USE OP2_FORTRAN_RT_SUPPORT
USE ISO_C_BINDING
USE kinds_mod,    ONLY: ink,rlk
USE parameters_mod,ONLY: LI


CONTAINS

!DEC$ ATTRIBUTES FORCEINLINE :: set_zero4
SUBROUTINE set_zero4(a)

    USE kinds_mod,ONLY: rlk

    implicit none

    REAL(KIND=rlk), DIMENSION(4), INTENT(OUT) :: a

    a(1:4) = 0.0_rlk

  END SUBROUTINE set_zero4


SUBROUTINE op_wrap_set_zero4( &
  & opDat1Local, &
  & bottom,top)
  real(8) opDat1Local(4,*)
  INTEGER(kind=4) bottom,top,i1

  DO i1 = bottom, top-1, 1
! kernel call
  CALL set_zero4( &
    & opDat1Local(1,i1+1) &
    & )
  END DO
END SUBROUTINE
SUBROUTINE set_zero4_host( userSubroutine, set, &
  & opArg1 )

  IMPLICIT NONE
  character(kind=c_char,len=*), INTENT(IN) :: userSubroutine
  type ( op_set ) , INTENT(IN) :: set

  type ( op_arg ) , INTENT(IN) :: opArg1

  type ( op_arg ) , DIMENSION(1) :: opArgArray
  INTEGER(kind=4) :: numberOfOpDats
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayStart
  INTEGER(kind=4), DIMENSION(1:8) :: timeArrayEnd
  REAL(kind=8) :: startTime
  REAL(kind=8) :: endTime
  INTEGER(kind=4) :: returnSetKernelTiming
  INTEGER(kind=4) :: n_upper
  type ( op_set_core ) , POINTER :: opSetCore

  real(8), POINTER, DIMENSION(:) :: opDat1Local
  INTEGER(kind=4) :: opDat1Cardinality


  INTEGER(kind=4) :: i1

  numberOfOpDats = 1

  opArgArray(1) = opArg1

  returnSetKernelTiming = setKernelTime(3 , userSubroutine//C_NULL_CHAR, &
  & 0.d0, 0.00000,0.00000, 0)
  call op_timers_core(startTime)

  n_upper = op_mpi_halo_exchanges(set%setCPtr,numberOfOpDats,opArgArray)

  opSetCore => set%setPtr

  opDat1Cardinality = opArg1%dim * getSetSizeFromOpArg(opArg1)
  CALL c_f_pointer(opArg1%data,opDat1Local,(/opDat1Cardinality/))


  CALL op_mpi_wait_all(numberOfOpDats,opArgArray)
  CALL op_wrap_set_zero4( &
  & opDat1Local, &
  & 0, n_upper)

  CALL op_mpi_set_dirtybit(numberOfOpDats,opArgArray)

  call op_timers_core(endTime)

  returnSetKernelTiming = setKernelTime(3 , userSubroutine//C_NULL_CHAR, &
  & endTime-startTime,0.00000,0.00000, 1)
END SUBROUTINE
END MODULE